### ISSUE TITLE
Get from structs

### ISSUE THREAD

**Issue by dvv** [mtannaan/elixpath#7]
Hello!

Couldn't you extend the code to cope with structs?

This is well:
```
%{id: "123"} |> Elixpath.query(".:id")
{:ok, ["123"]}
```

This isn't:
```
x                                     
%Repo.Catalog.Category{
  __meta__: #Ecto.Schema.Metadata<:loaded, "card_category">,
  enabled: true,
  id: "123",
  image: nil
}
x |> Elixpath.query(".:id")
{:ok, []}
```

TIA

**Comment by mtannaan** [comment]
Thanks for your feedback :-)

As of now, we can get your expected behavior by implementing a callback for the struct:

```elixir
defimpl Elixpath.Access, for: Repo.Catalog.Category do
  def query(data, key, opts), do: Elixpath.Access.Map.query(data, key, opts)
end
```


I'm not sure if we should change the behavior of the existing code, but if the above workaround does not help you much we could also consider adding a syntax sugar for it 🤔

**Comment by dvv** [comment]
Thank you a lot!
Done.
